# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rturk}
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mark Percival"]
  s.date = %q{2009-10-26}
  s.email = %q{mark@mpercival.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     ".gitmodules",
     ".yardoc",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "TODO.markdown",
     "VERSION",
     "examples/blank_slate.rb",
     "examples/create_hit.rb",
     "examples/mturk.sample.yml",
     "examples/newtweet.html",
     "examples/review_answer.rb",
     "lib/rturk.rb",
     "lib/rturk/adapters/answers.rb",
     "lib/rturk/adapters/assignment.rb",
     "lib/rturk/adapters/hit.rb",
     "lib/rturk/builders/qualification_builder.rb",
     "lib/rturk/builders/qualifications_builder.rb",
     "lib/rturk/builders/question_builder.rb",
     "lib/rturk/errors.rb",
     "lib/rturk/logger.rb",
     "lib/rturk/macros.rb",
     "lib/rturk/operation.rb",
     "lib/rturk/operations/approve_assignment.rb",
     "lib/rturk/operations/create_hit.rb",
     "lib/rturk/operations/disable_hit.rb",
     "lib/rturk/operations/dispose_hit.rb",
     "lib/rturk/operations/force_expire_hit.rb",
     "lib/rturk/operations/get_account_balance.rb",
     "lib/rturk/operations/get_assignments_for_hit.rb",
     "lib/rturk/operations/get_hit.rb",
     "lib/rturk/operations/get_reviewable_hits.rb",
     "lib/rturk/operations/grant_bonus.rb",
     "lib/rturk/operations/reject_assignment.rb",
     "lib/rturk/requester.rb",
     "lib/rturk/response.rb",
     "lib/rturk/responses/create_hit_response.rb",
     "lib/rturk/responses/get_account_balance_response.rb",
     "lib/rturk/responses/get_assignments_for_hit_response.rb",
     "lib/rturk/responses/get_hit_response.rb",
     "lib/rturk/responses/get_reviewable_hits_response.rb",
     "lib/rturk/utilities.rb",
     "lib/rturk/xml_utilities.rb",
     "rturk.gemspec",
     "spec/adapters/answers_spec.rb",
     "spec/adapters/assignment_spec.rb",
     "spec/adapters/hit_spec.rb",
     "spec/builders/qualification_spec.rb",
     "spec/builders/qualifications_spec.rb",
     "spec/builders/question_spec.rb",
     "spec/fake_responses/approve_assignment.xml",
     "spec/fake_responses/create_hit.xml",
     "spec/fake_responses/disable_hit.xml",
     "spec/fake_responses/dispose_hit.xml",
     "spec/fake_responses/force_expire_hit.xml",
     "spec/fake_responses/get_account_balance.xml",
     "spec/fake_responses/get_assignments.xml",
     "spec/fake_responses/get_hit.xml",
     "spec/fake_responses/get_reviewable_hits.xml",
     "spec/fake_responses/grant_bonus.xml",
     "spec/fake_responses/invalid_credentials.xml",
     "spec/fake_responses/reject_assignment.xml",
     "spec/mturk.sample.yml",
     "spec/operations/approve_assignment_spec.rb",
     "spec/operations/create_hit_spec.rb",
     "spec/operations/disable_hit_spec.rb",
     "spec/operations/dispose_hit_spec.rb",
     "spec/operations/force_expire_hit_spec.rb",
     "spec/operations/get_account_balance_spec.rb",
     "spec/operations/get_assignments_spec.rb",
     "spec/operations/get_hit_spec.rb",
     "spec/operations/get_reviewable_hits_spec.rb",
     "spec/operations/grant_bonus_spec.rb",
     "spec/operations/reject_assignment_spec.rb",
     "spec/requester_spec.rb",
     "spec/response_spec.rb",
     "spec/rturk_spec.rb",
     "spec/spec_helper.rb",
     "spec/tmp",
     "spec/xml_parse_spec.rb"
  ]
  s.homepage = %q{http://github.com/markpercival/rturk}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Mechanical Turk API Wrapper}
  s.test_files = [
    "spec/adapters/answers_spec.rb",
     "spec/adapters/assignment_spec.rb",
     "spec/adapters/hit_spec.rb",
     "spec/builders/qualification_spec.rb",
     "spec/builders/qualifications_spec.rb",
     "spec/builders/question_spec.rb",
     "spec/operations/approve_assignment_spec.rb",
     "spec/operations/create_hit_spec.rb",
     "spec/operations/disable_hit_spec.rb",
     "spec/operations/dispose_hit_spec.rb",
     "spec/operations/force_expire_hit_spec.rb",
     "spec/operations/get_account_balance_spec.rb",
     "spec/operations/get_assignments_spec.rb",
     "spec/operations/get_hit_spec.rb",
     "spec/operations/get_reviewable_hits_spec.rb",
     "spec/operations/grant_bonus_spec.rb",
     "spec/operations/reject_assignment_spec.rb",
     "spec/requester_spec.rb",
     "spec/response_spec.rb",
     "spec/rturk_spec.rb",
     "spec/spec_helper.rb",
     "spec/xml_parse_spec.rb",
     "examples/blank_slate.rb",
     "examples/create_hit.rb",
     "examples/review_answer.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
